package brain

import (
	"crypto/sha256"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

type DedupEntry struct {
	Topic   string
	Line    string
	LineNum int
}

type DedupGroup struct {
	Fingerprint  string
	Message      string
	Kept         DedupEntry
	Duplicates   []DedupEntry
	IsCrossTopic bool
}

type DedupReport struct {
	Groups         []DedupGroup
	TotalRemoved   int
	CrossTopicCount int
	ArchivedPath   string
}

func contentFingerprint(content string) string {
	normalized := normalizeEntry(content)
	h := sha256.Sum256([]byte(normalized))
	return fmt.Sprintf("%x", h[:8])
}

func FindDuplicates() ([]DedupGroup, error) {
	brainDir, err := FindBrainDir()
	if err != nil {
		return nil, err
	}

	topics := []string{"architecture", "decisions", "gotchas", "memory", "patterns"}

	type entryWithFP struct {
		topic       string
		line        string
		lineNum     int
		fingerprint string
		message     string
	}

	var allEntries []entryWithFP

	for _, topic := range topics {
		path := filepath.Join(brainDir, topic+".md")
		data, err := os.ReadFile(path)
		if err != nil {
			if os.IsNotExist(err) {
				continue
			}
			return nil, fmt.Errorf("reading %s.md: %w", topic, err)
		}

		lines := strings.Split(string(data), "\n")
		for i, line := range lines {
			if strings.HasPrefix(line, "### [") {
				msg := extractMessageFromEntry(line)
				fp := contentFingerprint(msg)
				allEntries = append(allEntries, entryWithFP{
					topic:       topic,
					line:        line,
					lineNum:     i + 1,
					fingerprint: fp,
					message:     normalizeEntry(msg),
				})
			}
		}
	}

	fpMap := make(map[string][]entryWithFP)
	for _, e := range allEntries {
		fpMap[e.fingerprint] = append(fpMap[e.fingerprint], e)
	}

	var groups []DedupGroup
	for fp, entries := range fpMap {
		if len(entries) < 2 {
			continue
		}

		sort.Slice(entries, func(i, j int) bool {
			if entries[i].topic != entries[j].topic {
				return entries[i].topic < entries[j].topic
			}
			return entries[i].lineNum < entries[j].lineNum
		})

		topicsInGroup := make(map[string]bool)
		for _, e := range entries {
			topicsInGroup[e.topic] = true
		}

		groups = append(groups, DedupGroup{
			Fingerprint:  fp,
			Message:      entries[0].message,
			Kept:         DedupEntry{Topic: entries[0].topic, Line: entries[0].line, LineNum: entries[0].lineNum},
			Duplicates:   nil,
			IsCrossTopic: len(topicsInGroup) > 1,
		})
		for _, e := range entries[1:] {
			groups[len(groups)-1].Duplicates = append(groups[len(groups)-1].Duplicates, DedupEntry{
				Topic:   e.topic,
				Line:    e.line,
				LineNum: e.lineNum,
			})
		}
	}

	sort.Slice(groups, func(i, j int) bool {
		return len(groups[i].Duplicates) > len(groups[j].Duplicates)
	})

	return groups, nil
}

func RunDedup(dryRun bool) (*DedupReport, error) {
	groups, err := FindDuplicates()
	if err != nil {
		return nil, err
	}

	report := &DedupReport{
		Groups: groups,
	}

	if len(groups) == 0 {
		return report, nil
	}

	dupLines := make(map[string]bool)
	for _, g := range groups {
		for _, d := range g.Duplicates {
			dupLines[d.Topic+"_"+d.Line] = true
		}
	}

	brainDir, err := FindBrainDir()
	if err != nil {
		return nil, err
	}

	topics := []string{"architecture", "decisions", "gotchas", "memory", "patterns"}

	for _, topic := range topics {
		path := filepath.Join(brainDir, topic+".md")
		data, err := os.ReadFile(path)
		if err != nil {
			if os.IsNotExist(err) {
				continue
			}
			return nil, fmt.Errorf("reading %s.md: %w", topic, err)
		}

		lines := strings.Split(string(data), "\n")
		var kept []string
		for _, line := range lines {
			if dupLines[topic+"_"+line] {
				continue
			}
			kept = append(kept, line)
		}

		if len(kept) != len(lines) {
			if !dryRun {
				if err := os.WriteFile(path, []byte(strings.Join(kept, "\n")), 0600); err != nil {
					return nil, fmt.Errorf("writing %s.md: %w", topic, err)
				}
			}
		}
	}

	totalRemoved := 0
	crossTopicCount := 0
	for _, g := range groups {
		totalRemoved += len(g.Duplicates)
		if g.IsCrossTopic {
			crossTopicCount++
		}
	}
	report.TotalRemoved = totalRemoved
	report.CrossTopicCount = crossTopicCount

	if !dryRun {
		archivedDir := filepath.Join(brainDir, "archived")
		if err := os.MkdirAll(archivedDir, 0755); err != nil {
			return nil, fmt.Errorf("creating archived dir: %w", err)
		}

		archivePath := filepath.Join(archivedDir, fmt.Sprintf("dedup-%s.md", time.Now().Format("2006-01-02")))
		report.ArchivedPath = archivePath

		var archive strings.Builder
		archive.WriteString(fmt.Sprintf("# Archived Duplicates — %s\n\n", time.Now().Format("2006-01-02")))
		archive.WriteString("Generated by: brain dedup\n")
		archive.WriteString(fmt.Sprintf("Total entries archived: %d\n\n", totalRemoved))

		byTopic := make(map[string][]DedupEntry)
		for _, g := range groups {
			for _, d := range g.Duplicates {
				byTopic[d.Topic] = append(byTopic[d.Topic], d)
			}
		}

		for _, topic := range topics {
			entries, ok := byTopic[topic]
			if !ok {
				continue
			}

			archive.WriteString(fmt.Sprintf("## From %s.md\n\n", topic))
			for _, d := range entries {
				msg := extractMessageFromEntry(d.Line)
				archive.WriteString(fmt.Sprintf("### [archived %s] (was line %d)\n%s\n\n",
					time.Now().Format("2006-01-02"), d.LineNum, msg))
			}
		}

		if err := os.WriteFile(archivePath, []byte(archive.String()), 0600); err != nil {
			return nil, fmt.Errorf("writing archive: %w", err)
		}
	}

	return report, nil
}
