package otel

import "go.opentelemetry.io/otel/attribute"

const (
	BrainCommand       = attribute.Key("brain.command")
	BrainVersion       = attribute.Key("brain.version")
	BrainProfile       = attribute.Key("brain.profile")
	BrainEntryID       = attribute.Key("brain.entry.id")
	BrainEntryTopic    = attribute.Key("brain.entry.topic")
	BrainEntryTopics   = attribute.Key("brain.entry.topics")
	BrainEntryContent  = attribute.Key("brain.entry.content")
	BrainEntryConfidence = attribute.Key("brain.entry.confidence")
	BrainEntrySource   = attribute.Key("brain.entry.source")
	BrainEntryDecision = attribute.Key("brain.entry.decision")
	BrainEntryFingerprint = attribute.Key("brain.entry.fingerprint")
	BrainReviewMode    = attribute.Key("brain.review.mode")
	BrainReviewTotal   = attribute.Key("brain.review.total")
	BrainReviewAccepted = attribute.Key("brain.review.accepted")
	BrainReviewRejected = attribute.Key("brain.review.rejected")
	BrainReviewDuplicates = attribute.Key("brain.review.duplicates")
	BrainDaemonItem    = attribute.Key("brain.daemon.item")
	BrainDaemonRepo    = attribute.Key("brain.daemon.repo")
	BrainDaemonAttempt = attribute.Key("brain.daemon.attempt")
	BrainDaemonOutcome = attribute.Key("brain.daemon.outcome")
	BrainDaemonQueuePending = attribute.Key("brain.daemon.queue.pending")
	BrainDiffSize      = attribute.Key("brain.diff.size_bytes")
	BrainDiffFiles     = attribute.Key("brain.diff.files_changed")
	BrainSecretsFound  = attribute.Key("brain.secrets.found")
	BrainSecretsTypes  = attribute.Key("brain.secrets.types")
	BrainLLMProvider   = attribute.Key("brain.llm.provider")
	BrainLLMModel      = attribute.Key("brain.llm.model")
	BrainLLMLatencyMs  = attribute.Key("brain.llm.latency_ms")
	BrainLLMConfidence = attribute.Key("brain.llm.confidence")
	BrainFindingsGotchas = attribute.Key("brain.findings.gotchas")
	BrainFindingsPatterns = attribute.Key("brain.findings.patterns")
	BrainFindingsDecisions = attribute.Key("brain.findings.decisions")
	BrainFindingsArchitecture = attribute.Key("brain.findings.architecture")
	BrainIndexEntries  = attribute.Key("brain.index.entries")
	BrainIndexSaveMs   = attribute.Key("brain.index.save_ms")
	BrainDurationMs    = attribute.Key("brain.duration_ms")
	BrainOutcome       = attribute.Key("brain.outcome")
)
